// GENERATED by scripts/build_ghayat_course.py — do not hand-edit.
//
// The third level: «غاية المريد في علم التجويد» لعطية قابل نصر,
// 374 pages, read from the copy this app hosts as `ghayat_al_murid`.
//
// Each lesson is a run of the BOOK'S OWN table-of-contents sections,
// ending where the author ends it — every block closes with his own
// «أسئلة». Nothing here is written by the app; the ranges only say
// which of his paragraphs belong together.
library;

/// One lesson: a span of the book, inclusive at both ends.
///
/// Addressed by the index of the page in the book's `pages` array, not
/// by its printed number: this book puts several sections on one printed
/// page (two of them are on page 23), so the printed number does not
/// identify a place. [printedFrom] and [printedTo] are what the reader
/// is shown.
class GhayatLesson {
  final String title;
  final int fromIndex;
  final int fromPara;
  final int toIndex;
  final int toPara;
  final int printedFrom;
  final int printedTo;

  const GhayatLesson({
    required this.title,
    required this.fromIndex,
    required this.fromPara,
    required this.toIndex,
    required this.toPara,
    required this.printedFrom,
    required this.printedTo,
  });
}

/// The book these lessons are read from — hosted, downloaded on first use.
const ghayatBook = 'ghayat_al_murid';

const ghayatLessons = <GhayatLesson>[
  GhayatLesson(
    title: 'مدخل إلى علم التجويد',
    fromIndex: 4,
    fromPara: 0,
    toIndex: 21,
    toPara: 13,
    printedFrom: 9,
    printedTo: 21,
  ),
  GhayatLesson(
    title: 'تاريخ التجويد والقراءات',
    fromIndex: 22,
    fromPara: 0,
    toIndex: 34,
    toPara: 9,
    printedFrom: 22,
    printedTo: 29,
  ),
  GhayatLesson(
    title: 'الإمام عاصم وراويه حفص',
    fromIndex: 35,
    fromPara: 0,
    toIndex: 41,
    toPara: 4,
    printedFrom: 30,
    printedTo: 34,
  ),
  GhayatLesson(
    title: 'أقسام التجويد ومعنى اللحن',
    fromIndex: 42,
    fromPara: 0,
    toIndex: 54,
    toPara: 5,
    printedFrom: 35,
    printedTo: 43,
  ),
  GhayatLesson(
    title: 'الاستعاذة',
    fromIndex: 55,
    fromPara: 0,
    toIndex: 57,
    toPara: 6,
    printedFrom: 44,
    printedTo: 46,
  ),
  GhayatLesson(
    title: 'البسملة وأوجه الابتداء',
    fromIndex: 58,
    fromPara: 0,
    toIndex: 64,
    toPara: 8,
    printedFrom: 47,
    printedTo: 50,
  ),
  GhayatLesson(
    title: 'أحكام النون الساكنة والتنوين',
    fromIndex: 65,
    fromPara: 0,
    toIndex: 67,
    toPara: 5,
    printedFrom: 51,
    printedTo: 53,
  ),
  GhayatLesson(
    title: 'الإظهار الحلقي',
    fromIndex: 68,
    fromPara: 0,
    toIndex: 71,
    toPara: 7,
    printedFrom: 54,
    printedTo: 56,
  ),
  GhayatLesson(
    title: 'الإدغام',
    fromIndex: 72,
    fromPara: 0,
    toIndex: 77,
    toPara: 9,
    printedFrom: 57,
    printedTo: 62,
  ),
  GhayatLesson(
    title: 'الإقلاب',
    fromIndex: 78,
    fromPara: 0,
    toIndex: 80,
    toPara: 11,
    printedFrom: 63,
    printedTo: 65,
  ),
  GhayatLesson(
    title: 'الإخفاء الحقيقي',
    fromIndex: 81,
    fromPara: 0,
    toIndex: 86,
    toPara: 7,
    printedFrom: 66,
    printedTo: 70,
  ),
  GhayatLesson(
    title: 'النون والميم المشددتان والغنة',
    fromIndex: 87,
    fromPara: 0,
    toIndex: 91,
    toPara: 8,
    printedFrom: 71,
    printedTo: 73,
  ),
  GhayatLesson(
    title: 'أحكام الميم الساكنة',
    fromIndex: 92,
    fromPara: 0,
    toIndex: 100,
    toPara: 11,
    printedFrom: 74,
    printedTo: 81,
  ),
  GhayatLesson(
    title: 'أحكام اللامات السواكن',
    fromIndex: 101,
    fromPara: 0,
    toIndex: 114,
    toPara: 7,
    printedFrom: 82,
    printedTo: 89,
  ),
  GhayatLesson(
    title: 'المد والقصر: الأصلي والفرعي',
    fromIndex: 115,
    fromPara: 0,
    toIndex: 134,
    toPara: 1,
    printedFrom: 91,
    printedTo: 103,
  ),
  GhayatLesson(
    title: 'المد اللازم وأقسامه ومراتب المدود',
    fromIndex: 135,
    fromPara: 0,
    toIndex: 143,
    toPara: 14,
    printedFrom: 106,
    printedTo: 112,
  ),
  GhayatLesson(
    title: 'تنبيهات المدود وألقابها',
    fromIndex: 144,
    fromPara: 0,
    toIndex: 159,
    toPara: 8,
    printedFrom: 113,
    printedTo: 122,
  ),
  GhayatLesson(
    title: 'مخارج الحروف',
    fromIndex: 160,
    fromPara: 0,
    toIndex: 178,
    toPara: 11,
    printedFrom: 124,
    printedTo: 136,
  ),
  GhayatLesson(
    title: 'صفات الحروف',
    fromIndex: 179,
    fromPara: 0,
    toIndex: 201,
    toPara: 11,
    printedFrom: 137,
    printedTo: 156,
  ),
  GhayatLesson(
    title: 'التفخيم والترقيق',
    fromIndex: 202,
    fromPara: 0,
    toIndex: 220,
    toPara: 11,
    printedFrom: 157,
    printedTo: 170,
  ),
  GhayatLesson(
    title: 'المتماثلان والمتقاربان والمتجانسان والمتباعدان',
    fromIndex: 221,
    fromPara: 0,
    toIndex: 232,
    toPara: 12,
    printedFrom: 171,
    printedTo: 180,
  ),
  GhayatLesson(
    title: 'الوقف على أواخر الكلم',
    fromIndex: 233,
    fromPara: 0,
    toIndex: 241,
    toPara: 9,
    printedFrom: 181,
    printedTo: 189,
  ),
  GhayatLesson(
    title: 'حكم التقاء الساكنين',
    fromIndex: 242,
    fromPara: 0,
    toIndex: 247,
    toPara: 5,
    printedFrom: 190,
    printedTo: 195,
  ),
  GhayatLesson(
    title: 'الحذف والإثبات',
    fromIndex: 248,
    fromPara: 0,
    toIndex: 268,
    toPara: 2,
    printedFrom: 196,
    printedTo: 214,
  ),
  GhayatLesson(
    title: 'هاء الكناية',
    fromIndex: 269,
    fromPara: 0,
    toIndex: 273,
    toPara: 9,
    printedFrom: 216,
    printedTo: 219,
  ),
  GhayatLesson(
    title: 'الوقف والابتداء',
    fromIndex: 274,
    fromPara: 0,
    toIndex: 295,
    toPara: 11,
    printedFrom: 220,
    printedTo: 238,
  ),
  GhayatLesson(
    title: 'المقطوع والموصول',
    fromIndex: 296,
    fromPara: 0,
    toIndex: 325,
    toPara: 9,
    printedFrom: 239,
    printedTo: 263,
  ),
  GhayatLesson(
    title: 'هاء التأنيث الموقوف عليها بالتاء',
    fromIndex: 326,
    fromPara: 0,
    toIndex: 341,
    toPara: 10,
    printedFrom: 265,
    printedTo: 278,
  ),
  GhayatLesson(
    title: 'همزتا الوصل والقطع',
    fromIndex: 342,
    fromPara: 0,
    toIndex: 358,
    toPara: 10,
    printedFrom: 279,
    printedTo: 289,
  ),
  GhayatLesson(
    title: 'ما يراعى لحفص وخاتمة الكتاب',
    fromIndex: 359,
    fromPara: 0,
    toIndex: 364,
    toPara: 5,
    printedFrom: 290,
    printedTo: 295,
  ),
];
