// GENERATED by scripts/build_jazariyyah_sharh.py — do not hand-edit.
//
// Each Jazariyyah lesson's part of «فتح رب البرية شرح المقدمة الجزرية»
// (صفوت محمود سالم، Shamela 21580), located by the lesson's first verse.
// Indices address `BookText.pages` and the paragraphs `BookText` keeps.
library;

class JazariyyahSharhRange {
  final int fromIndex;
  final int fromPara;
  final int toIndex;
  final int toPara;

  /// This lesson's verses and a neighbour's stand in one block in the
  /// شرح and are explained together, so both lessons carry this range.
  final bool shared;

  const JazariyyahSharhRange(
    this.fromIndex,
    this.fromPara,
    this.toIndex,
    this.toPara, {
    this.shared = false,
  });
}

const jazariyyahSharhBook = 'fath_rabb_al_bariyyah_sharh_al_jazariyyah';

/// One entry per lesson, in `jazariyyahLessons` order.
const jazariyyahSharhRanges = <JazariyyahSharhRange>[
  JazariyyahSharhRange(5, 0, 6, 0),
  JazariyyahSharhRange(7, 0, 11, 9),
  JazariyyahSharhRange(12, 0, 22, 9),
  JazariyyahSharhRange(23, 0, 25, 8),
  JazariyyahSharhRange(26, 0, 27, 7),
  JazariyyahSharhRange(28, 0, 29, 12),
  JazariyyahSharhRange(30, 0, 34, 10, shared: true),
  JazariyyahSharhRange(30, 0, 34, 10, shared: true),
  JazariyyahSharhRange(35, 0, 41, 14, shared: true),
  JazariyyahSharhRange(35, 0, 41, 14, shared: true),
  JazariyyahSharhRange(42, 0, 45, 5),
  JazariyyahSharhRange(46, 0, 53, 7),
  JazariyyahSharhRange(54, 0, 59, 5),
  JazariyyahSharhRange(60, 0, 70, 5),
  JazariyyahSharhRange(71, 0, 79, 4),
  JazariyyahSharhRange(80, 0, 81, 6),
  JazariyyahSharhRange(82, 0, 84, 9, shared: true),
  JazariyyahSharhRange(82, 0, 84, 9, shared: true),
];
