// GENERATED by scripts/build_jazariyyah_course.py — do not hand-edit.
//
// The second level: «المقدمة الجزرية» لابن الجزري (ت ٨٣٣ هـ).
//
// EIGHTEEN LESSONS, AND NOT ONE LINE OF THE EDITOR'S. The printing is
// د. عبد المحسن القاسم's 2020 edition, whose apparatus — مقدمة التحقيق,
// وصف النسخ, ترجمة الناظم, نماذج من المخطوطات, فهرس المراجع — is his own
// work and stays out. These ranges cover entries 18 to 35 of the book's
// table of contents: the nazim's poem, from «مقدمة الناظم» to his
// «[خاتمة]».
library;

/// One lesson: a span of the matn, inclusive at both ends, addressed by
/// index into `BookText.pages` for the reason `GhayatLesson` explains.
class JazariyyahLesson {
  final String title;
  final int fromIndex;
  final int fromPara;
  final int toIndex;
  final int toPara;
  final int printedFrom;
  final int printedTo;

  const JazariyyahLesson({
    required this.title,
    required this.fromIndex,
    required this.fromPara,
    required this.toIndex,
    required this.toPara,
    required this.printedFrom,
    required this.printedTo,
  });
}

const jazariyyahBook = 'al_muqaddimah_al_jazariyyah_matn';

const jazariyyahLessons = <JazariyyahLesson>[
  JazariyyahLesson(
    title: 'مقدمة الناظم',
    fromIndex: 50,
    fromPara: 0,
    toIndex: 52,
    toPara: 1,
    printedFrom: 53,
    printedTo: 56,
  ),
  JazariyyahLesson(
    title: 'في معرفة مخارج الحروف',
    fromIndex: 53,
    fromPara: 0,
    toIndex: 55,
    toPara: 3,
    printedFrom: 56,
    printedTo: 59,
  ),
  JazariyyahLesson(
    title: 'في صفات الحروف',
    fromIndex: 56,
    fromPara: 0,
    toIndex: 58,
    toPara: 1,
    printedFrom: 59,
    printedTo: 62,
  ),
  JazariyyahLesson(
    title: 'في التجويد',
    fromIndex: 59,
    fromPara: 0,
    toIndex: 60,
    toPara: 4,
    printedFrom: 62,
    printedTo: 64,
  ),
  JazariyyahLesson(
    title: 'في الترقيقات',
    fromIndex: 61,
    fromPara: 0,
    toIndex: 64,
    toPara: 1,
    printedFrom: 64,
    printedTo: 68,
  ),
  JazariyyahLesson(
    title: 'في الراءات',
    fromIndex: 65,
    fromPara: 0,
    toIndex: 65,
    toPara: 4,
    printedFrom: 68,
    printedTo: 69,
  ),
  JazariyyahLesson(
    title: 'في اللامات',
    fromIndex: 66,
    fromPara: 0,
    toIndex: 66,
    toPara: 2,
    printedFrom: 69,
    printedTo: 70,
  ),
  JazariyyahLesson(
    title: 'في التحذيرات',
    fromIndex: 67,
    fromPara: 0,
    toIndex: 68,
    toPara: 4,
    printedFrom: 70,
    printedTo: 72,
  ),
  JazariyyahLesson(
    title: 'في الظاءات',
    fromIndex: 69,
    fromPara: 0,
    toIndex: 72,
    toPara: 2,
    printedFrom: 72,
    printedTo: 76,
  ),
  JazariyyahLesson(
    title: 'في التحذيرات',
    fromIndex: 73,
    fromPara: 0,
    toIndex: 74,
    toPara: 2,
    printedFrom: 76,
    printedTo: 78,
  ),
  JazariyyahLesson(
    title: 'في معرفة النون الساكنة والتنوين',
    fromIndex: 75,
    fromPara: 0,
    toIndex: 76,
    toPara: 2,
    printedFrom: 78,
    printedTo: 80,
  ),
  JazariyyahLesson(
    title: 'في المدات',
    fromIndex: 77,
    fromPara: 0,
    toIndex: 77,
    toPara: 5,
    printedFrom: 80,
    printedTo: 81,
  ),
  JazariyyahLesson(
    title: 'في الوقوف',
    fromIndex: 78,
    fromPara: 0,
    toIndex: 80,
    toPara: 1,
    printedFrom: 81,
    printedTo: 84,
  ),
  JazariyyahLesson(
    title: 'في المقطوع والموصول',
    fromIndex: 81,
    fromPara: 0,
    toIndex: 86,
    toPara: 2,
    printedFrom: 84,
    printedTo: 90,
  ),
  JazariyyahLesson(
    title: 'في التاءات',
    fromIndex: 87,
    fromPara: 0,
    toIndex: 91,
    toPara: 1,
    printedFrom: 90,
    printedTo: 95,
  ),
  JazariyyahLesson(
    title: 'في همزات الوصل',
    fromIndex: 92,
    fromPara: 0,
    toIndex: 92,
    toPara: 4,
    printedFrom: 95,
    printedTo: 96,
  ),
  JazariyyahLesson(
    title: 'في الوقف على أواخر الكلم',
    fromIndex: 93,
    fromPara: 0,
    toIndex: 93,
    toPara: 3,
    printedFrom: 96,
    printedTo: 97,
  ),
  JazariyyahLesson(
    title: 'خاتمة',
    fromIndex: 94,
    fromPara: 0,
    toIndex: 96,
    toPara: 1,
    printedFrom: 97,
    printedTo: 100,
  ),
];
