// GENERATED by scripts/build_tamhid_course.py — do not hand-edit.
//
// The third level: «التمهيد في علم التجويد» لابن الجزري (ت ٨٣٣ هـ),
// read from the copy this app hosts as `at_tamhid_fi_ilm_at_tajwid`.
// Its author died in 1429; nothing in it belongs to anyone living.
//
// Each lesson is a run of the BOOK'S OWN table-of-contents sections:
// one باب with its فصول, ending where he ends it. Nothing here is
// written by the app; the ranges only say which of his paragraphs
// belong together. The editor's apparatus is not in this text at all
// — 986 body paragraphs, 42 headings, 26 ayahs, and no footnote.
library;

/// One lesson: a span of the book, inclusive at both ends.
///
/// Addressed by the index of the page in the book's `pages` array and
/// the index of the paragraph inside it, not by the printed number: a
/// section can open halfway down a page — «القول في كلا» starts at the
/// fourth paragraph of the page the باب before it ends on — so a printed
/// number does not identify a place. [printedFrom] and [printedTo] are
/// what the reader is shown.
class TamhidLesson {
  final String title;
  final int fromIndex;
  final int fromPara;
  final int toIndex;
  final int toPara;
  final int printedFrom;
  final int printedTo;

  const TamhidLesson({
    required this.title,
    required this.fromIndex,
    required this.fromPara,
    required this.toIndex,
    required this.toPara,
    required this.printedFrom,
    required this.printedTo,
  });
}

/// The book these lessons are read from — hosted, downloaded on first use.
const tamhidBook = 'at_tamhid_fi_ilm_at_tajwid';

const tamhidLessons = <TamhidLesson>[
  TamhidLesson(
    title: 'مقدمة ابن الجزري',
    fromIndex: 0,
    fromPara: 0,
    toIndex: 2,
    toPara: 9,
    printedFrom: 39,
    printedTo: 39,
  ),
  TamhidLesson(
    title: 'الباب الأول: قراءة القراء في هذا الزمان',
    fromIndex: 3,
    fromPara: 0,
    toIndex: 6,
    toPara: 1,
    printedFrom: 43,
    printedTo: 45,
  ),
  TamhidLesson(
    title: 'الباب الثاني: معنى التجويد والتحقيق والترتيل',
    fromIndex: 7,
    fromPara: 0,
    toIndex: 11,
    toPara: 8,
    printedFrom: 47,
    printedTo: 51,
  ),
  TamhidLesson(
    title: 'الباب الثالث: أصول القراءة',
    fromIndex: 12,
    fromPara: 0,
    toIndex: 18,
    toPara: 1,
    printedFrom: 53,
    printedTo: 53,
  ),
  TamhidLesson(
    title: 'الباب الرابع: اللحن وأقسامه',
    fromIndex: 19,
    fromPara: 0,
    toIndex: 21,
    toPara: 6,
    printedFrom: 61,
    printedTo: 62,
  ),
  TamhidLesson(
    title: 'الباب الخامس: ألفات الوصل والقطع',
    fromIndex: 22,
    fromPara: 0,
    toIndex: 30,
    toPara: 2,
    printedFrom: 65,
    printedTo: 72,
  ),
  TamhidLesson(
    title: 'الباب السادس: الحركات والحروف',
    fromIndex: 31,
    fromPara: 0,
    toIndex: 37,
    toPara: 1,
    printedFrom: 75,
    printedTo: 78,
  ),
  TamhidLesson(
    title: 'الباب السابع: ألقاب الحروف وصفاتها',
    fromIndex: 38,
    fromPara: 0,
    toIndex: 57,
    toPara: 1,
    printedFrom: 83,
    printedTo: 102,
  ),
  TamhidLesson(
    title: 'الباب الثامن: مخارج الحروف وتجويد كل حرف',
    fromIndex: 58,
    fromPara: 0,
    toIndex: 104,
    toPara: 1,
    printedFrom: 105,
    printedTo: 107,
  ),
  TamhidLesson(
    title: 'الباب التاسع: النون الساكنة والتنوين والمد',
    fromIndex: 105,
    fromPara: 0,
    toIndex: 114,
    toPara: 7,
    printedFrom: 153,
    printedTo: 161,
  ),
  TamhidLesson(
    title: 'الباب العاشر: الوقف والابتداء',
    fromIndex: 115,
    fromPara: 0,
    toIndex: 127,
    toPara: 2,
    printedFrom: 165,
    printedTo: 175,
  ),
  TamhidLesson(
    title: 'القول في الكلمات الموقوف عليها والمشددات',
    fromIndex: 127,
    fromPara: 3,
    toIndex: 158,
    toPara: 5,
    printedFrom: 177,
    printedTo: 207,
  ),
  TamhidLesson(
    title: 'معرفة الظاء وتمييزها من الضاد',
    fromIndex: 159,
    fromPara: 0,
    toIndex: 173,
    toPara: 5,
    printedFrom: 209,
    printedTo: 209,
  ),
];
