import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:rafeeq_app/features/library/data/book_text.dart';
import 'package:rafeeq_app/features/tajweed/data/ghayat_course.dart';
import 'package:rafeeq_app/features/tajweed/data/ghayat_lesson_text.dart';

/// The third level is thirty claims about where a 374-page book's paragraphs
/// are. `flutter analyze` cannot check one of them.
///
/// The ranges are generated by `scripts/build_ghayat_course.py`, which counts
/// paragraphs over the raw JSON — while the app counts them **after**
/// `BookText` has dropped Shamela's noise lines. Those two counts disagreed by
/// 34 paragraphs on the first run, which would have shifted the later lessons
/// by that much: correct-looking titles over somebody else's text. This test
/// is the side that matters, because it reads the book through the app's own
/// parser, exactly as the screen does.
///
/// The fixture is the very file the app hosts as `ghayat_al_murid`.
void main() {
  late BookText book;

  setUpAll(() {
    book = BookText.fromJson(
      jsonDecode(File('test/fixtures/ghayat_al_murid.json').readAsStringSync())
          as Map<String, dynamic>,
    );
  });

  test('the level is the whole book, not a sample of it', () {
    expect(ghayatLessons.length, 30);
    expect(ghayatLessons.first.printedFrom, 9);
    expect(ghayatLessons.last.printedTo, 295);
  });

  test('every lesson opens on its own heading', () {
    final wrong = <String>[];
    for (final l in ghayatLessons) {
      final paras = ghayatLessonParas(l, book);
      if (paras.isEmpty) {
        wrong.add('${l.title}: empty');
        continue;
      }
      if (ghayatBare(paras.first.text) != ghayatBare(l.title)) {
        wrong.add('${l.title}: opens on "${paras.first.text}"');
      }
    }
    expect(wrong, isEmpty,
        reason: 'a lesson whose first paragraph is not its heading is a lesson '
            'pointing at the wrong place:\n${wrong.join('\n')}');
  });

  test('no lesson runs past the book, or backwards', () {
    for (final l in ghayatLessons) {
      expect(l.fromIndex, inInclusiveRange(0, book.pages.length - 1),
          reason: l.title);
      expect(l.toIndex, inInclusiveRange(0, book.pages.length - 1),
          reason: l.title);
      expect(l.fromIndex, lessThanOrEqualTo(l.toIndex), reason: l.title);
      expect(l.fromPara,
          inInclusiveRange(0, book.pages[l.fromIndex].paras.length - 1),
          reason: l.title);
      expect(
          l.toPara, inInclusiveRange(0, book.pages[l.toIndex].paras.length - 1),
          reason: l.title);
      if (l.fromIndex == l.toIndex) {
        expect(l.fromPara, lessThanOrEqualTo(l.toPara), reason: l.title);
      }
    }
  });

  test('the lessons run in order and do not overlap or skip', () {
    for (var i = 1; i < ghayatLessons.length; i++) {
      final prev = ghayatLessons[i - 1];
      final next = ghayatLessons[i];
      // The next lesson starts exactly one paragraph after the previous ends.
      if (next.fromPara > 0) {
        expect(next.fromIndex, prev.toIndex,
            reason: '${next.title} starts on a different page than '
                '${prev.title} ends, with no page boundary between them');
        expect(next.fromPara, prev.toPara + 1, reason: next.title);
      } else {
        expect(next.fromIndex, greaterThan(prev.toIndex), reason: next.title);
      }
    }
  });

  test('every lesson has real text in it', () {
    for (final l in ghayatLessons) {
      final paras = ghayatLessonParas(l, book);
      // The thinnest lesson in the book is the closing one; nothing should be
      // under ten paragraphs, and an empty one would render as «يلزم تنزيل
      // نصّ الدروس» under a correct title.
      expect(paras.length, greaterThan(10), reason: l.title);
      expect(paras.map((p) => p.text.trim()).where((t) => t.isEmpty), isEmpty,
          reason: l.title);
    }
  });

  test('the course really covers pages 9 to 295 without a gap', () {
    var paragraphs = 0;
    for (final l in ghayatLessons) {
      paragraphs += ghayatLessonParas(l, book).length;
    }
    // 3,102 as the generator counted them. A drift here means the two sides
    // have stopped agreeing about what a paragraph is.
    expect(paragraphs, 3102);
  });
}
