// GENERATED by scripts/build_assistant_settings_map.py - do not edit.
// Each settings section: its SettingsPart and the translation keys
// shown inside it (its own title first).

const assistantSettingsSections = <String, (String, List<String>)>{
  'settings.language': ('settings', [
  ]),
  'settings.theme': ('settings', [
    'settings.motion_effects',
  ]),
  'assistant.setting_title': ('settings', [
    'assistant.pack_delete',
    'assistant.pack_download',
    'assistant.pack_failed',
    'assistant.pack_needed',
    'assistant.pack_title',
    'assistant.setting_switch',
  ]),
  'settings.font_section': ('settings', [
    'settings.font_sample',
  ]),
  'settings.splash_section': ('settings', [
    'settings.splash_preview',
    'settings.splash_preview_play',
    'settings.splash_video',
    'settings.splash_video_sound',
  ]),
  'home.clock_section': ('settings', [
    'home.clock_12h',
    'home.clock_gallery_title',
    'home.clock_seconds',
    'home.clock_style',
  ]),
  'mushaf_theme.title': ('settings', [
    'mushaf_theme.subtitle',
    'settings.live_preview',
    'settings.non_arabic_reading_title',
    'settings.show_transliteration',
  ]),
  'settings.permissions': ('settings', [
    'settings.perm_autostart',
    'settings.perm_battery',
    'settings.perm_battery_revoked',
    'settings.perm_full_screen',
    'settings.perm_location',
    'settings.perm_notifications',
  ]),
  'library.voice_section_title': ('settings', [
    'library.open_voice_title',
    'library.open_voice_use_device',
    'library.voice_open_fallback_note',
  ]),
  'sunan_suwar.reminders_section_title': ('reminders', [
    'sunan_suwar.reminder_off',
    'sunan_suwar.reminder_on_at',
  ]),
  'tasbih.section_title': ('reminders', [
    'tasbih.desc',
    'tasbih.off',
    'tasbih.window',
  ]),
  'fasting.section_title': ('reminders', [
    'fasting.calendar_note',
    'fasting.mon_thu',
    'fasting.note',
    'fasting.time',
    'fasting.time_other',
    'fasting.white_days',
  ]),
  'quotes.section_title': ('reminders', [
    'quotes.home_card',
    'quotes.off',
    'quotes.preview',
    'quotes.reminder_desc_plain',
    'quotes.reminder_title',
  ]),
};
