"""Generate rafeeq_app/lib/features/assistant/data/assistant_settings_map.dart.

For «رفيق» to open a setting where it IS (owner, 2026-09-27: «يفتح اي حاجة
في التطبيق ... في اي خرم ابرة»), it has to know which settings section holds
each thing a reader might name. That is read here from the settings screen
itself, so a setting added later is covered by re-running this, not by
remembering to update a list:

  every `CollapsibleSection(title: '<key>'.tr(), ...)` in settings_screen.dart
  -> its SettingsPart (the `if (part == SettingsPart.x)` block it sits in)
  -> every '<ns.key>'.tr( inside its block, plus inside the widget classes the
     block builds (one level: the class's own file under lib/).

    py -3 scripts/build_assistant_settings_map.py
"""
import os
import re

ROOT = os.path.join(os.path.dirname(__file__), '..', 'rafeeq_app')
LIB = os.path.join(ROOT, 'lib')
SCREEN = os.path.join(LIB, 'features', 'settings', 'presentation', 'screens',
                      'settings_screen.dart')
OUT = os.path.join(LIB, 'features', 'assistant', 'data',
                   'assistant_settings_map.dart')

KEY = re.compile(r"'([a-z_]+\.[a-z0-9_.]+)'\.tr\(")
CLASS_USE = re.compile(r'\b(?:const\s+)?([A-Z][A-Za-z0-9]+)\(')


def class_files():
    out = {}
    decl = re.compile(r'^class ([A-Z][A-Za-z0-9]+)\b', re.M)
    for d, _, fs in os.walk(LIB):
        for f in fs:
            if f.endswith('.dart'):
                p = os.path.join(d, f)
                for c in decl.findall(open(p, encoding='utf-8').read()):
                    out.setdefault(c, p)
    return out


def main():
    src = open(SCREEN, encoding='utf-8').read()
    body = src[src.index('class SettingsBody'):src.index('class CollapsibleSection')]
    files = class_files()
    parts = [(m.start(), m.group(1)) for m in
             re.finditer(r'if \(part == SettingsPart\.(\w+)\)', body)]
    starts = [m.start() for m in re.finditer(r'CollapsibleSection\(', body)]
    sections = []
    for i, s in enumerate(starts):
        end = min([starts[i + 1] if i + 1 < len(starts) else len(body)] +
                  [pos for (pos, _) in parts if pos > s])
        block = body[s:end]
        title = KEY.search(block).group(1)
        part = [p for (pos, p) in parts if pos < s][-1]
        keys = set(KEY.findall(block))
        for c in set(CLASS_USE.findall(block)):
            f = files.get(c)
            if f and f != SCREEN:
                keys |= set(KEY.findall(open(f, encoding='utf-8').read()))
        # Descriptions, hints and error texts are sentences, not names.
        keys = {k for k in keys if not re.search(r'(_desc|_hint|_loading)$', k)
                and not k.startswith(('errors.', 'common.', 'app.'))}
        sections.append((title, part, sorted(keys - {title})))
    lines = [
        '// GENERATED by scripts/build_assistant_settings_map.py - do not edit.',
        '// Each settings section: its SettingsPart and the translation keys',
        '// shown inside it (its own title first).',
        '',
        'const assistantSettingsSections = <String, (String, List<String>)>{',
    ]
    for title, part, keys in sections:
        lines.append(f"  '{title}': ('{part}', [")
        for k in keys:
            lines.append(f"    '{k}',")
        lines.append('  ]),')
    lines.append('};')
    open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
    print(len(sections), 'sections,', sum(len(k) for _, _, k in sections), 'keys ->', OUT)


main()
