"""Library book id -> its Shamela book id, read from each book's own file.

The app's catalogue (book_catalog.dart) does not carry the Shamela id; every
book's built JSON does (`meta.shamelaId`). The in-app Shamela import uses
this map to mark a Shamela book the library already has («موجود في مكتبتك»,
owner 2026-09-26) and to open that copy instead of importing it again.

Sources, in order: scripts/book_text_build/<id>.json, the app's built-in
books, then the copy hosted on R2. A book built from PART of a Shamela book
is left out on purpose (al_fiqh_al_manhaji_hajj = only the Hajj chapters of
6369): marking the whole book «موجود» would say something untrue.

    py -3 scripts/build_shamela_catalogue_ids.py
"""
import gzip, io, json, os, re, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.join(HERE, "..", "rafeeq_app")
PARTIAL = {"al_fiqh_al_manhaji_hajj"}
R2 = "https://pub-39dbef68a1a845d5ba669b43a59516b9.r2.dev/books/text/%s.json"


def meta(book_id):
    for p in (os.path.join(HERE, "book_text_build", book_id + ".json"),
              os.path.join(APP, "assets", "data", "builtin_books", book_id + ".json")):
        if os.path.exists(p):
            raw = open(p, "rb").read()
            break
    else:
        req = urllib.request.Request(R2 % book_id, headers={"User-Agent": "rafeeq-audit (int.vip00)"})
        raw = urllib.request.urlopen(req, timeout=60).read()
    if raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)
    return json.loads(raw.decode("utf-8")).get("meta", {})


cat = io.open(os.path.join(APP, "lib", "features", "library", "data", "book_catalog.dart"), encoding="utf-8").read()
ids = sorted(set(re.findall(r"LibraryBook\(\s*id: '([^']+)'", cat)))
out, missing = {}, []
for b in ids:
    if b in PARTIAL:
        continue
    sid = meta(b).get("shamelaId")
    if sid:
        out[b] = int(sid)
    else:
        missing.append(b)
lines = ["// GENERATED by scripts/build_shamela_catalogue_ids.py - do not edit.",
         "// Library book id -> Shamela book id, from each book's own meta.",
         "// %d of %d catalogue books; left out: %s." % (len(out), len(ids), ", ".join(sorted(PARTIAL | set(missing)))),
         "const Map<String, int> shamelaIdOfLibraryBook = {"]
lines += ["  '%s': %d," % (k, v) for k, v in sorted(out.items())]
lines += ["};", ""]
p = os.path.join(APP, "lib", "features", "shamela", "data", "shamela_catalogue_ids.dart")
io.open(p, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
print(len(out), "of", len(ids), "mapped; missing:", missing)
