"""Shared R2 plumbing — credentials and, more importantly, a CA bundle that
actually works on this machine.

**The trap this exists for.** Uploading to R2 with boto3 fails here with

    SSLError: ... CERTIFICATE_VERIFY_FAILED: unable to get local issuer
    certificate

even though `curl` to the same endpoint is fine. Two separate causes stack up:

1. **Avast is intercepting TLS.** Reading the certificate the endpoint
   actually presents shows

       issuer = CN=Avast Web/Mail Shield Root,
                OU=generated by Avast Antivirus for SSL/TLS scanning

   Avast's "Web Shield" terminates TLS and re-signs with its own root. That
   root is installed in the **Windows** certificate store, so curl, Chrome and
   anything else using the OS store trust it — but `certifi`'s bundle is a
   fixed list of public CAs and will never contain it.

2. **R2 sends only the leaf certificate**, with no intermediate. curl chases
   the issuer through the certificate's AIA extension; Python's `ssl` module
   does not do AIA fetching at all, so even without Avast a bare certifi
   bundle can fail here.

The fix is to verify against the machine's own root store — the same trust
curl is already using — instead of turning verification off. **Never pass
`verify=False`:** these requests carry the bucket's access key and secret, and
sending them down an unverified connection is not an acceptable shortcut.

Set `RAFEEQ_CA_BUNDLE` to override the whole mechanism with a bundle of your
own.
"""

import os
import subprocess
import sys
import tempfile

import certifi

ENV_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
BUCKET = "rafeeq-content"

_CACHED = os.path.join(tempfile.gettempdir(), "rafeeq_ca_bundle.pem")

_EXPORT_PS = r"""
$sb = New-Object System.Text.StringBuilder
foreach ($store in @("Cert:\LocalMachine\Root","Cert:\CurrentUser\Root","Cert:\LocalMachine\CA")) {
  if (Test-Path $store) {
    Get-ChildItem $store | ForEach-Object {
      $b64 = [System.Convert]::ToBase64String($_.RawData, 'InsertLineBreaks')
      [void]$sb.AppendLine("-----BEGIN CERTIFICATE-----")
      [void]$sb.AppendLine($b64)
      [void]$sb.AppendLine("-----END CERTIFICATE-----")
    }
  }
}
[Console]::Out.Write($sb.ToString())
"""


def ca_bundle(refresh=False):
    """Path to a PEM holding certifi's roots plus the Windows trust store.

    Cached in the temp dir; pass refresh=True (or delete the file) to rebuild
    after installing or removing a root certificate.
    """
    override = os.environ.get("RAFEEQ_CA_BUNDLE")
    if override:
        return override

    if not refresh and os.path.isfile(_CACHED) and os.path.getsize(_CACHED) > 0:
        return _CACHED

    parts = [open(certifi.where(), encoding="utf-8").read()]

    if sys.platform == "win32":
        try:
            res = subprocess.run(
                ["powershell", "-NoProfile", "-Command", _EXPORT_PS],
                capture_output=True,
                text=True,
                timeout=120,
            )
            if res.returncode == 0 and "BEGIN CERTIFICATE" in res.stdout:
                parts.append(res.stdout)
            else:
                print(
                    "warning: could not read the Windows root store; "
                    "falling back to certifi only",
                    file=sys.stderr,
                )
        except Exception as e:  # noqa: BLE001 - diagnostics only
            print(f"warning: Windows root export failed: {e}", file=sys.stderr)

    with open(_CACHED, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    return _CACHED


def load_env(path=ENV_PATH):
    """Reads `scripts/.env`. Never print what this returns."""
    env = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
    return env


def r2_client():
    """A boto3 S3 client for the `rafeeq-content` bucket, verifying properly."""
    import boto3

    env = load_env()
    return boto3.client(
        "s3",
        endpoint_url=env["R2_ENDPOINT"],
        aws_access_key_id=env["R2_ACCESS_KEY_ID"],
        aws_secret_access_key=env["R2_SECRET_ACCESS_KEY"],
        region_name="auto",
        verify=ca_bundle(),
    )
